name = "WhatsThePoint"
uuid = "5faae8f1-f507-432f-bd56-cf2f1161ab6f"
version = "0.1.1"
authors = ["Kyle Beggs <beggskw@gmail.com>"]

[deps]
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
CoordRefSystems = "b46f11dc-f210-4604-bfba-323c1ec968cb"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeoIO = "f5a160d5-e41d-4189-8b61-d57781c419e3"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
WhatsThePointMakieExt = "Makie"

[compat]
ChunkSplitters = "3"
CoordRefSystems = "0.19"
Distances = "0.10.1"
FileIO = "1.16"
GeoIO = "1.21.5"
Graphs = "1.7"
Makie = "0.24"
Meshes = "0.56"
NearestNeighbors = "0.4.8"
OhMyThreads = "0.7, 0.8"
OrderedCollections = "1.7.0"
PrecompileTools = "1.2"
ProgressMeter = "1.7"
SimpleWeightedGraphs = "1.2.2"
StaticArrays = "1.9"
Statistics = "1"
StructArrays = "0.6, 0.7"
Unitful = "1.20"
WriteVTK = "1.18"
julia = "1.10"
